package domain

// ClarificationResponse represents a clarification message generated by the LLM
type ClarificationResponse struct {
	Message   string `json:"message"`
	Candidate string `json:"candidate,omitempty"`
}

// SmartClarificationResponse represents an enhanced clarification with Hololive-relatedness check
type SmartClarificationResponse struct {
	IsHololiveRelated bool   `json:"is_hololive_related"`
	Message          string  `json:"message"`
	Candidate        string  `json:"candidate,omitempty"`
}
